---
'on': push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: oidc
        name: Run colpal/actions-google-sa-to-oidc
        uses: ./
        with:
          sa_key: ${{ secrets.VAULT_IAP_SA }}
          target_audience: ${{ secrets.VAULT_IAP_CLIENT_ID }}

      - id: vault
        uses: hashicorp/vault-action@v2.1.0
        with:
          url: https://public.vault.colpal.cloud
          method: approle
          roleId: 774e2757-4579-c411-4d04-68477ccf19ff
          secretId: ${{ secrets.VAULT_SECRET_ID }}
          secrets: secret/data/hello-world/user-pass password
          exportEnv: false
          extraHeaders: |
            Authorization: Bearer ${{ steps.oidc.outputs.token }}

      - run: test "$CHECKSUM" = "$(md5sum <<< "$PASSWORD")"
        env:
          PASSWORD: ${{ steps.vault.outputs.password }}
          CHECKSUM: f0f849454b9e638f6f760df83ed72d94
